[project]
name = "social-media-research"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.6.1",
    "python-dotenv==1.2.1",
    "typer==0.20.0",
    "xai-sdk==1.3.1",
]
